---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sivacloud-app
  labels:
    app: pandacloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sivacloud-app
  template:
    metadata:
      labels:
        app: sivacloud-app
    spec:
      containers:
      - name: sivacloud-container
        image: 820242928550.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
